UKSM: fix compile errors
mm/uksm.c:183:0: error: "U64_MAX" redefined [-Werror]

 #define U64_MAX  (~((u64)0))

mm/uksm.c:1607:10: error: implicit declaration of function 'compound_trans_head' [-Werror=implicit-function-declaration]

   struct page *head = compound_trans_head(page);

mm/uksm.c:169:23: error: initialization discards 'const' qualifier from pointer target type [-Werror]

  unsigned long *src = s1;

Signed-off-by: UpInTheAir <upintheair.xda@gmail.com>

Conflicts:
	include/linux/kernel.h